spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**
          filters:
            - StripPrefix=1

        - id: program-service
          uri: lb://program-service
          predicates:
            - Path=/api/v1/programs/**
          filters:
            - StripPrefix=1

        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/v1/enrollments/**
          filters:
            - StripPrefix=1

      default-filters:
        - PreserveHostHeader

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 7000
  address: 0.0.0.0