server:
  port: 7000
  address: 0.0.0.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/v1/students/**, /api/v1/students

        - id: program-service
          uri: lb://PROGRAM-SERVICE
          predicates:
            - Path=/api/v1/programs/**, /api/v1/programs

        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/api/v1/enrollments/**, /api/v1/enrollments

      default-filters:
        - PreserveHostHeader

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"