spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**

        - id: program-service
          uri: lb://program-service
          predicates:
            - Path=/api/v1/programs/**

        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/v1/enrollments/**

      default-filters:
        - PreserveHostHeader

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 7000